apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-svc-a
  name: hello-world-svc-a
spec:
  ports:
  - name: hello-world-svc-a
    port: 80
    targetPort: 8080
  selector:
    app: hello-world-deployment-a
status:
  loadBalancer: {}